import test from 'node:test';
import assert from 'node:assert/strict';
import { utils, write, read } from 'xlsx';
import JSZip from 'jszip';
import { readInput } from '../src/importer.js';
import { normalizeRows, sha256, analyze } from '../src/core.js';
import { createPackage, openPackage, readBounded } from '../src/packages.js';
import { exportWorkbook, exportPdf, safeCell } from '../src/exports.js';
import { IseqClient } from '../src/iseq.js';
function workbookFile(array, sheetName = 'Dados brutos') { const wb = utils.book_new(); utils.book_append_sheet(wb, utils.aoa_to_sheet(array), sheetName); return new File([write(wb, { type: 'array', bookType: 'xlsx' })], 'controle.xlsx'); }
const units = { CO2: { unit: 'ppm', confirmed: true } };
async function fixture() { const bytes = new TextEncoder().encode('entrada controlada'), hash = await sha256(bytes); const normalized = normalizeRows([{ data_local: '2026-10-01 00:00', CO2: 500 }, { data_local: '2026-10-01 00:01', CO2: 700 }], { format: 'wide', date: 'data_local', columns: { CO2: 'CO2' } }, { sensorId: 'CONTROL', offsetMinutes: -180, units }, hash.slice(0, 16)); const dataset = { id: 'case', name: 'Controle sintético', environment: 'escola', synthetic: true, sensorId: 'CONTROL', sensorLabel: 'Controle', offsetMinutes: -180, nominalIntervalSeconds: 60, units, sources: [{ id: hash.slice(0, 16), name: 'input.txt', hash, bytes, size: bytes.length, rows: 2, origin: 'synthetic' }], observations: normalized.observations, issues: [], decisions: [], hasInputs: true }; const analysis = analyze(dataset, { parameter: 'CO2', window: 'hour', start: Date.UTC(2026, 9, 1, 3), end: Date.UTC(2026, 9, 1, 4) }); return { dataset, run: { id: 'execution', createdAt: '2026-10-08T00:00:00Z', caseName: dataset.name, datasetId: 'case', offsetMinutes: -180, analysis } }; }
test('Excel amplo conserva linhas vazias e números originais', async () => { const input = await readInput(workbookFile([['data_local', 'CO2'], ['2026-10-01 00:00', 500], [null, null], ['2026-10-01 00:02', 700]])); const sheet = input.sheets[0]; assert.equal(sheet.rows.length, 3); const result = normalizeRows(sheet.rows, sheet.mapping, { sensorId: 'CONTROL', offsetMinutes: -180, units }, 'source'); assert.equal(result.observations[1].rowNumber, 4); assert.equal(result.rejectedRows, 1); });
test('Excel longo ISEQ reconhece parâmetro, unidade e valor', async () => { const input = await readInput(workbookFile([['Timestamp (Local)', 'Parâmetro solicitado', 'Valor', 'Unidade'], ['2026-10-01 00:00', 'CO2', '600,5', 'ppm']], 'Dados')); const sheet = input.sheets[0]; assert.equal(sheet.mapping.format, 'long'); const output = normalizeRows(sheet.rows, sheet.mapping, { sensorId: 'CONTROL', offsetMinutes: -180, units }, 'source'); assert.equal(output.observations[0].value, 600.5); assert.equal(output.observations[0].originalUnit, 'ppm'); });
test('pacote completo restaura originais e resultados sem recalcular', async () => { const { dataset, run } = await fixture(); const saved = await createPackage(dataset, run, [run], true); const opened = await openPackage(new File([saved], 'case.aircase')); assert.deepEqual(opened.run, run); assert.equal(opened.dataset.observations.length, 2); assert.equal(await sha256(opened.dataset.sources[0].bytes), dataset.sources[0].hash); });
test('pacote compartilhável omite originais e observações individuais', async () => { const { dataset, run } = await fixture(); const saved = await createPackage(dataset, run, [run], false); const opened = await openPackage(new File([saved], 'shared.aircase')); assert.equal(opened.dataset.observations.length, 0); assert.equal(opened.dataset.hasInputs, false); assert.equal(opened.dataset.sources[0].bytes, undefined); assert.deepEqual(opened.run.analysis, run.analysis); });
test('pacote alterado é recusado por integridade', async () => { const { dataset, run } = await fixture(); const blob = await createPackage(dataset, run, [run], true); const zip = await JSZip.loadAsync(await blob.arrayBuffer()); zip.file('execution.json', JSON.stringify({ hacked: true })); const altered = await zip.generateAsync({ type: 'uint8array' }); await assert.rejects(() => openPackage(new File([altered], 'bad.aircase')), /Integridade divergente/); });
test('PDF e Excel derivam da mesma execução e células textuais são neutralizadas', async () => { const { dataset, run } = await fixture(); assert.equal(safeCell('=HYPERLINK("x")'), "'=HYPERLINK(\"x\")"); const wb = read(await exportWorkbook(dataset, run).arrayBuffer(), { type: 'array' }); const rows = utils.sheet_to_json(wb.Sheets.Resultados); assert.equal(rows[0].media, 600); assert.equal(rows[0].execucao, 'execution'); const header = new TextDecoder().decode(new Uint8Array(await exportPdf(dataset, run).arrayBuffer()).slice(0, 5)); assert.equal(header, '%PDF-'); });
test('conector ISEQ é inerte antes da ação de login e pagina histórico com sessão em memória', async () => { const calls = []; const fetcher = async (url, options) => { calls.push({ url, options }); let body; if (url.endsWith('/health')) body = { status: 'ok', auth_ready: true }; else if (url.endsWith('/login')) body = { session_token: 'synthetic-session', equipment: [{ mac: 'CONTROL', label: 'Exemplo' }] }; else if (url.endsWith('/jobs')) body = { id: 'job-1' }; else if (url.endsWith('/job-1')) body = { status: 'completed' }; else body = { rows: [{ data_local: '2026-10-01 00:00', CO2: 600 }], has_more: false }; return { ok: true, json: async () => body }; }; const client = new IseqClient('https://example.invalid', fetcher); assert.equal(calls.length, 0); await client.login('synthetic-user', 'synthetic-password'); const result = await client.historical('CONTROL', '2026-10-01', '2026-10-02', new AbortController().signal); assert.equal(result.rows.length, 1); assert.equal(calls[2].options.headers.Authorization, 'Bearer synthetic-session'); assert.ok(!JSON.stringify(client).includes('synthetic-session')); });
test('arquivo com sensores misturados é recusado antes da análise', async () => { await assert.rejects(() => readInput(workbookFile([['data_local', 'sensor_id', 'CO2'], ['2026-10-01 00:00', 'SCHOOL', 500], ['2026-10-01 00:00', 'HOSPITAL', 900]])), /vários sensores/); });
test('descompactação é interrompida ao exceder o limite, antes de juntar todo o conteúdo', async () => { const zip = new JSZip(); zip.file('large.txt', 'x'.repeat(100000)); const loaded = await JSZip.loadAsync(await zip.generateAsync({ type: 'uint8array', compression: 'DEFLATE' })); await assert.rejects(() => readBounded(loaded.file('large.txt'), 1000), /excede o limite/); });
